# Generated by Django 5.1.2 on 2024-10-09 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_creationdate_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muatation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
