# Generated by Django 5.1.2 on 2024-10-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mutation_delete_muatation_alter_account_creationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='calculatedBalance',
        ),
        migrations.AddField(
            model_name='mutation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
